# Generated by Django 4.0.3 on 2022-03-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='naghavi', max_length=255),
        ),
    ]
